version: '3.4'

services:
  codeflix.catalog.db:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  default:
    name: service_catalog
      